### ISSUE TITLE
해결 해야 되는 버그

### ISSUE THREAD

**Issue by dktmzdf** [loveljhs2/Invisible_hand_in_class#1]
- 파일 손실 및 파일 전송 실패
   UDP 특성상 검사를 안하다보니 파일 손실은 물론이고 메세지를 제대로 못 받는 경우가 생겨요. 예를 들어서 end of file 메세지가 없어져서 서버가 쓰다가 멈춰버리고 성공한다 쳐도 300kb가 150kb~160kb만 남은 문제가 생겨요. 클라이언트쪽에서 어떻게 구현하는지 알려주면 그에 따라 고쳐 볼께요.
- 폴더 생성 문제
   이쪽은 서버 쪽의 문제인데 서버쪽에서 받는 파일을 temp라는 폴더에 저장해요. 따라서 폴더가 없을 경우 폴더를 만드는데, 문제는 폴더를 만들고나서 프로그램이 죽어버려요. 이쪽은 계속해서 찾아볼께요.
- 임시 파일 문제
   이쪽도 서버쪽 문제인데 서버쪽에서 파일 받는 방식이 일단 temp.dat 이라는 임시 파일 생성 후 임시 파일에 데이터를 쓴 뒤, 임시 파일 데이터를 temp 폴더 아래 파일에 복사한 후 임시파일을 삭제 하는 방식이에요. 다만 문제점이 임시파일이 없어질때도 있고 그냥 남아버리는 경우도 있어요. 코드만 어찌 고치면 될 것 같은데 잘 안되네요.

**Comment by sohnji-ss** [comment]
- 파일 손실 및 파일 전송 실패
UDP 특성상 검사를 안하다보니 파일 손실은 물론이고 메세지를 제대로 못 받는 경우가 생겨요. 
 : 일단 저는 end of  file 메세지를 파일 뒤에다가 붙이는 것이 아닌 문자열 형식으로 그 문자열만 보낼려한는데,,, 이 부분은 나중에 같이 확인 해보도록 해요
