### ISSUE TITLE
한글 인코딩 문제

### ISSUE THREAD

**Issue by sohnji-ss** [loveljhs2/Invisible_hand_in_class#3]
주석 처리 부분을 한글로 했는데, 인코딩 문제 같은데 어떻게 처리 할까요?

**Comment by loveljhs2** [comment]
일단 본인이 사용하는 개발, 관리 툴을 모두 인코딩 타입을 UTF-8로 맞춰서 진행을 하면 될 것 같아요. 
서로서로 인코딩 타입이 달라서 그런것 같으니까 이렇게 해봐요
